// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCltDgfsAVnoLfm37KI57KwMKXB0ZZAmrs',
    appId: '1:898413129742:web:f7a1dc877af25372584c5f',
    messagingSenderId: '898413129742',
    projectId: 'e-com-7d952',
    authDomain: 'e-com-7d952.firebaseapp.com',
    storageBucket: 'e-com-7d952.firebasestorage.app',
    measurementId: 'G-PC3EHSY4BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfr2xEV2ROihEyxdHuoVYuFabxpVibQIw',
    appId: '1:898413129742:android:0e3adb8e39a3b0e6584c5f',
    messagingSenderId: '898413129742',
    projectId: 'e-com-7d952',
    storageBucket: 'e-com-7d952.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKAT_-dlTJq6vk9osEsWbuutzfW2pYJwU',
    appId: '1:898413129742:ios:554836dcf1df3f4f584c5f',
    messagingSenderId: '898413129742',
    projectId: 'e-com-7d952',
    storageBucket: 'e-com-7d952.firebasestorage.app',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKAT_-dlTJq6vk9osEsWbuutzfW2pYJwU',
    appId: '1:898413129742:ios:554836dcf1df3f4f584c5f',
    messagingSenderId: '898413129742',
    projectId: 'e-com-7d952',
    storageBucket: 'e-com-7d952.firebasestorage.app',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCltDgfsAVnoLfm37KI57KwMKXB0ZZAmrs',
    appId: '1:898413129742:web:184d092771c212ea584c5f',
    messagingSenderId: '898413129742',
    projectId: 'e-com-7d952',
    authDomain: 'e-com-7d952.firebaseapp.com',
    storageBucket: 'e-com-7d952.firebasestorage.app',
    measurementId: 'G-CZ1D03XXHR',
  );
}
